language: scala
jdk:
  - oraclejdk8
sudo: false

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

script:
  - sbt -jvm-opts travis/jvmopts.compile "^ compile"
  - sbt -jvm-opts travis/jvmopts.test test "^ scripted"

deploy:
  provider: script
  script: sbt publish & sbt ^^1.0.0 publish
  on:
    tags: true
    all_branches: true