language: scala
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt -jvm-opts travis/jvmopts.compile "^ compile"
  - sbt -jvm-opts travis/jvmopts.test test "^ scripted"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: script
  script: sbt publish
  on:
    tags: true
    all_branches: true